version: "3.3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: off-on-farm
    ports:
      - 8090:8090
    volumes:
      - ./.env:/app/.env:Z
      - ../files:/app/files/:Z
